FROM node:16-alpine AS build

RUN mkdir /app

WORKDIR /app

COPY frontend/package.json .

RUN npm install

COPY frontend/ .

RUN npm run build

FROM node:16-alpine

WORKDIR /app

COPY --from=build /app/dist .

RUN npm install -g serve

CMD ["serve", "-s", ".", "-p", "80"]